services:
  backend:
    image: huzaifaaneel42/aici:backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  frontend:
    image: huzaifaaneel42/aici:frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
